name: Freelexity
description: "An open-source answer engine built with Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.1.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  lottie: ^2.2.0
  iconsax: ^0.0.8
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  shimmer: ^2.0.0
  url_launcher: ^6.1.10
  fluttertoast: ^8.2.1
  intl: ^0.18.0
  html: ^0.15.1
  record: ^5.1.2
  path_provider: ^2.0.14
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.3
  sliding_up_panel: ^2.0.0+1
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
       android: true
       ios: false
       image_path: "assets/icon/icon.png"
       adaptive_icon_background: "#121212" # or any color
       adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true
  

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Medium.ttf
          weight: 500

  assets:
    - assets/
